### ISSUE TITLE
recursion: parse arguments from file

### ISSUE THREAD

**Issue by milahu** [ko1nksm/getoptions#40]
shameless duplicate of https://github.com/matejak/argbash/issues/158

tldr: replace the argument `@my-args.txt` with the contents of the `my-args.txt` file, allow recursion

challenge: string parsing without eval

**Comment by ko1nksm** [comment]
It is outside the scope of this project. You can read the arguments from the file yourself. And you can implement such a feature.

**example**

```sh
while read -r arg_name arg_value; do
  sest -- "#@" "$arg_name" "$arg_value"
done < "$args_file" 
```

This library is for parsing arguments. And does not support any means of reading arguments (from a file, etc.).
