### ISSUE TITLE
Missing information about how to use getoptions

### ISSUE THREAD

**Issue by shpoont** [ko1nksm/getoptions#44]
Overall, it looks like a good tool, with many features, but learning how to use it is very time intensive. While there are some examples, there is hardly any explanation in the documentation.

I still have some questions unanswered, for example
- What is the format of each of the following: "setup", "msg", "flag", "option", "param", and "disp"? Any others?
- What is "mode"? How can it be used?
- What is the difference between "parameter" and "option"?
- How do I define the required parameters?

In addition, while getoptions looks useful, it is difficult to understand how it works from the code.

**Comment by indigoviolet** [comment]
Does this help: https://github.com/ko1nksm/getoptions/blob/master/docs/References.md?

**Comment by ko1nksm** [comment]
Thanks @indigoviolet
